source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
xcodeproj 'EssentialSwiftTools.xcodeproj'

pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtils'
pod 'Alamofire'
pod 'SwiftyJSON', '~> 2.2.1'
pod 'SnapKit', '~> 0.12.0'
pod 'AFDateHelper'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Instabug'
pod 'TPKeyboardAvoiding'
